services:
  webui:
    image: "ghcr.io/peterclemenko/sd-webui-forge-docker:master"
    # build: .
    volumes:
      - "./data:/app/sd-webui"
    ports:
      - "7860:7860"
    environment:
      - "ARGS=--listen --enable-insecure-extension-acces"
      - "UI=auto"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
